debian_mirror: http://mirror.it.ubc.ca/debian/
base_packages_apt:
  - sudo
  - nano
  - git
  - neofetch
  - htop
  - curl
  - wget
  - unzip
  - zip
  - zsh
  - toilet
  - figlet
  - python3-pip
  - python3-venv
  - socat
  - screen
  - rsync

# The types of VM configs.
# These should match the name of template files in roles/vm-configs/templates.
managed_vm_types:
  - workstation
  - server

# PCI passthrough devices on krile.
# TODO: this smells a bit - this should probably go in host_vars/krile.yml
managed_vm_pci_devices:
  gpu1-rtx3090:
    description: 'bus 0x65 = RTX 3090 in first slot'
    devices:
      - bus: '0x65'
        slot: '0x00'
        function: '0x0'
        rom: 'Asus.RTX3090.24576.201013_2.rom'
      - bus: '0x65'
        slot: '0x00'
        function: '0x1'
  gpu2-rtx3090:
    description: 'bus 0x17 = RTX 3090 in second slot'
    devices:
      - bus: '0x17'
        slot: '0x00'
        function: '0x0'
        rom: 'Asus.RTX3090.24576.210308_1.rom'
      - bus: '0x17'
        slot: '0x00'
        function: '0x1'
  usb-controller:
    description: 'bus 0xb6 = USB controller in top 8x slot'
    devices:
      - bus: '0xb6'
        slot: '0x00'
        function: '0x0'
        managed: true

# Most VM settings should be managed via the Terraform config, not here.
# "type" should match one of the types in managed_vm_types, in group_vars/all.yml.
managed_vms:
  workstation-w11:
    type: workstation
    autostart: false
    is_windows: true
    cpus: 24
    mem_gb: 128
    disk_gb: 500
    net_vlan: 10
    pci_devices:
      - gpu1-rtx3090
      - usb-controller
  workstation-linux:
    type: workstation
    autostart: false
    enable_vnc: true
    is_windows: false
    cpus: 24
    mem_gb: 128
    disk_gb: 500
    net_vlan: 10
    pci_devices:
      - gpu1-rtx3090
      - usb-controller
  server-anima:
    type: server
    autostart: true
    is_windows: false
    enable_vnc: true
    cpus: 16
    mem_gb: 128
    disk_gb: 500
    net_vlan: 90
    # PCI devices for anima are dynamically merged
    pci_devices: []

# variables with names in this list are exposed to Terraform
terraform_vars:
  - managed_vms
  - libvirt_host

libvirt_host: krile.lan.aethernet.ca # temporary hack (famous last words)
dotfiles_github_user: avafloww

hypervisor_managed_vms_local_file: /opt/hypervisor/managed-vms.local.json
