- name: Get GPU count
  block:
    - shell: nvidia-smi -L | wc -l
      register: gpu_count
    - set_fact:
        gpu_count: '{{ gpu_count.stdout }}'

- debug: var=gpu_count

- name: Set /etc/motd
  template:
    src: motd.j2
    dest: /etc/motd
    owner: root
    group: root
    mode: 0644
