- name: Generate Terraform variables file
  hosts: localhost
  become: false
  tasks:
    - name: Collect variables for terraform.tfvars.json
      set_fact:
        tfvars: '{{ tfvars | default({}) | combine({item: vars[item]}) }}'
      loop: '{{ terraform_vars }}'

    - name: Generate terraform.tfvars.json
      copy:
        content: '{{ tfvars | to_nice_json }}'
        dest: terraform/terraform.tfvars.json
        mode: 0600

- name: Generate managed VM configurations
  hosts: hypervisor
  tasks:
    - import_role:
        name: hypervisor
        tasks_from: managed-vms
