- name: 'Setup Aethernet'
  hosts: aethernet
  roles:
    - handlers
    - aethernet

- name: 'Setup Aethernet: ML Lab'
  hosts: aethernet-ml-lab
  roles:
    - handlers
    - aethernet
    - aethernet-ml-lab
    - tailscale
