- name: Apply Terraform infrastructure
  hosts: hypervisor
  become: false
  serial: 1
  tasks:
    - name: Gather list of running libvirt domains
      command: virsh list --name --state-running
      register: running_vms
      check_mode: false

    - debug: var=running_vms.stdout_lines

    - name: terraform apply
      community.general.terraform:
        project_path: './terraform'
        state: present
        complex_vars: true
        parallelism: 1
        variables:
          libvirt_host: 'krile' # todo: this is a hack for now
          managed_vms: '{{ managed_vms }}'
          running_vms: '{{ running_vms.stdout_lines }}'
      register: tf_run
      delegate_to: localhost

    - debug: var=tf_run

    - debug: var=tf_run.stdout
