- name: Wait for connection
  hosts: aethernet-ml-lab
  gather_facts: false
  tasks:
    - wait_for_connection:
        timeout: 300
        sleep: 5

- name: Update /etc/motd on Aethernet ML lab hosts
  hosts: aethernet-ml-lab
  tasks:
    - import_role:
        name: aethernet-ml-lab
        tasks_from: motd
