- name: Generate managed VM configs
  template:
    src: '{{ item.value.type }}.xsl.j2'
    dest: 'terraform/xslt/generated/{{ item.key }}.xsl'
  loop: '{{ managed_vms | dict2items }}'
  become: false
  delegate_to: localhost
