- name: Clone hotplugger
  git:
    repo: 'https://github.com/avafloww/hotplugger.git'
    version: 'pyusb_port_number'
    dest: '{{ hotplugger.dir }}'
    force: true

- name: Create hotplugger virtualenv
  pip:
    virtualenv: '{{ hotplugger.dir }}/venv'
    virtualenv_command: '{{ ansible_python_interpreter }} -m venv'
    name:
      - pyyaml
      - pyusb

- name: Write hotplugger config
  template:
    src: hotplugger.yml.j2
    dest: '{{ hotplugger.dir }}/config.yaml'

- name: Add udev rules
  template:
    src: 99-usb-hotplug.rules.j2
    dest: /etc/udev/rules.d/99-usb-hotplug.rules
    owner: root
    group: root
    mode: 0644
  notify: reload-udev-rules
