- name: Set modprobe configuration for vfio
  template:
    src: vfio.conf.j2
    dest: /etc/modprobe.d/vfio.conf
    owner: root
    group: root
    mode: 0644
  notify: update-initramfs

- name: Add vfio boot options
  copy:
    src: vfio-grub.cfg
    dest: /etc/default/grub.d/vfio.cfg
  notify: update-grub

- name: sysctl kernel.sched_rt_runtime_us=-1
  sysctl:
    name: kernel.sched_rt_runtime_us
    value: -1
    state: present
    sysctl_set: yes
    reload: yes

- import_tasks: vfio-isolate.yml
