- name: Set modprobe configuration for vfio
  template:
    src: vfio.conf.j2
    dest: /etc/modprobe.d/vfio.conf
    owner: root
    group: root
    mode: 0644
  notify: update-initramfs

- name: Add vfio boot options
  copy:
    src: vfio-grub.cfg
    dest: /etc/default/grub.d/vfio.cfg
  notify: update-grub
