#cloud-config
package_update: true
package_upgrade: true
package_reboot_if_required: true
system_info:
  default_user:
    name: ava
    sudo: ALL=(ALL) NOPASSWD:ALL
users:
  - name: ava
    groups: [sudo, cdrom, floppy, audio, dip, video, plugdev, netdev]
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJfOWctBFA4KplM/dSGN0Db+wzZiVcaNmHtQ3a5/4IdU ava@Hydaelyn
ssh_pwauth: false
growpart:
  mode: auto
  devices: ['/']
  ignore_growroot_disabled: false
hostname: ${hostname}
fqdn: ${hostname}.${domain}
