- name: Assert that tailscale_key is defined
  assert:
    that:
      - tailscale_key is defined
    msg: "tailscale_key is not defined"

- name: Install Tailscale apt key
  apt_key:
    url: 'https://pkgs.tailscale.com/stable/debian/{{ ansible_distribution_release }}.noarmor.gpg'
    state: present

- name: Install Tailscale deb repository
  apt_repository:
    repo: 'deb https://pkgs.tailscale.com/stable/debian {{ ansible_distribution_release }} main'
    state: present

- name: Install Tailscale
  apt:
    name: tailscale
    state: present
  register: tailscale_install

- name: Check if Tailscale SSH should be enabled
  set_fact:
    tailscale_ssh_args: '--ssh={{ tailscale_ssh_enabled }}'
  when: tailscale_ssh_enabled is defined

- name: Enable Tailscale with defined key
  shell: tailscale up --authkey {{ tailscale_key }} {{ tailscale_ssh_args | default('') }}
  register: tailscale_enable

- debug:
    msg: "{{ tailscale_enable.stdout_lines + tailscale_enable.stderr_lines }}"

- name: Ensure Tailscale SSH users exist
  user:
    name: '{{ item }}'
    create_home: true
    shell: '/bin/bash'
    umask: '007'
    state: present
  loop: '{{ tailscale_ssh_users }}'
  when: tailscale_ssh_enabled is defined and tailscale_ssh_enabled and tailscale_ssh_users is defined
