- name: Assert that tailscale_key is defined
  assert:
    that:
      - tailscale_key is defined
    msg: "tailscale_key is not defined"

- name: Install Tailscale apt key
  apt_key:
    url: 'https://pkgs.tailscale.com/stable/debian/{{ ansible_distribution_release }}.noarmor.gpg'
    state: present

- name: Install Tailscale deb repository
  apt_repository:
    repo: 'deb https://pkgs.tailscale.com/stable/debian {{ ansible_distribution_release }} main'
    state: present

- name: Install Tailscale
  apt:
    name: tailscale
    state: present
  register: tailscale_install

- name: Get Tailscale status
  shell: tailscale status
  register: tailscale_status
  changed_when: false
  failed_when: false
  ignore_errors: true
  when: not tailscale_install.changed

- name: Enable Tailscale with defined key
  shell: tailscale up --authkey {{ tailscale_key }}
  register: tailscale_enable
  when: tailscale_install.changed or tailscale_status.rc != 0

- debug:
    msg: "{{ tailscale_enable.stdout_lines + tailscale_enable.stderr_lines }}"
  when: tailscale_install.changed or tailscale_status.rc != 0
