#!/bin/bash
kmsg() {
    echo "virtwsctl: $@" >/dev/kmsg
}

# start tpm
/usr/bin/swtpm socket \
  --ctrl type=unixio,path=/run/libvirt/qemu/swtpm/2-workstation-w11-swtpm.sock,mode=0600 \
  --tpmstate dir=/var/lib/libvirt/swtpm/089669ce-3316-4186-87ec-ae650bb07254/tpm2,mode=0600 \
  --log file=/var/log/swtpm/libvirt/qemu/workstation-w11-swtpm.log \
  --terminate --tpm2

# start qemu
/usr/bin/qemu-system-x86_64 \
  -S \
  -name guest=workstation-w11,debug-threads=on \
  -machine pc-q35-7.2,hpet=off,usb=off,smm=on,dump-guest-core=off,memory-backend=pc.ram \
  -drive if=pflash,format=raw,readonly,file=/usr/share/OVMF/OVMF_CODE_4M.ms.fd \
  -drive if=pflash,format=raw,file=/var/lib/libvirt/qemu/nvram/workstation-w11_VARS.fd \
  -accel kvm \
  -cpu host,hv-time=on,hv-relaxed=on,hv-vapic=on,hv-spinlocks=0x1fff,hv-vpindex=on,hv-synic=on,hv-reset=on \
  -m 65536 \
  -overcommit mem-lock=on \
  -smp 16,sockets=1,dies=1,cores=8,threads=2 \
  -uuid 089669ce-3316-4186-87ec-ae650bb07254 \
  -display none \
  -no-user-config \
  -nodefaults \
  -chardev socket,id=charmonitor,fd=32,server=on,wait=off \
  -mon chardev=charmonitor,id=monitor,mode=control \
  -rtc base=localtime,driftfix=slew \
  -global kvm-pit.lost_tick_policy=delay \
  -global ICH9-LPC.disable_s3=1 \
  -global ICH9-LPC.disable_s4=1 \
  -boot strict=on \
  -device pcie-root-port,port=8,chassis=1,id=pci.1,bus=pcie.0,multifunction=on,addr=0x1 \
  -device pcie-root-port,port=9,chassis=2,id=pci.2,bus=pcie.0,addr=0x1.0x1 \
  -device pcie-root-port,port=10,chassis=3,id=pci.3,bus=pcie.0,addr=0x1.0x2 \
  -device pcie-root-port,port=11,chassis=4,id=pci.4,bus=pcie.0,addr=0x1.0x3 \
  -device pcie-root-port,port=12,chassis=5,id=pci.5,bus=pcie.0,addr=0x1.0x4 \
  -device pcie-root-port,port=13,chassis=6,id=pci.6,bus=pcie.0,addr=0x1.0x5 \
  -device pcie-root-port,port=14,chassis=7,id=pci.7,bus=pcie.0,addr=0x1.0x6 \
  -device pcie-root-port,port=15,chassis=8,id=pci.8,bus=pcie.0,addr=0x1.0x7 \
  -device pcie-root-port,port=16,chassis=9,id=pci.9,bus=pcie.0,multifunction=on,addr=0x2 \
  -device pcie-root-port,port=17,chassis=10,id=pci.10,bus=pcie.0,addr=0x2.0x1 \
  -device nec-usb-xhci,id=usb0,p2=15,p3=15,bus=pci.3,addr=0x0 \
  -device nec-usb-xhci,id=usb1,p2=15,p3=15,bus=pci.4,addr=0x0 \
  -device virtio-scsi-pci,id=scsi0,bus=pci.2,addr=0x0 \
  -drive file=/var/lib/libvirt/images/workstation-w11.qcow2,format=qcow2,if=virtio,id=drive-scsi0-0-0-0,cache=none \
  -blockdev '{"driver":"file","filename":"/var/lib/libvirt/images/workstation-w11.qcow2","node-name":"libvirt-1-storage","auto-read-only":true,"discard":"unmap"}' \
  -blockdev '{"node-name":"libvirt-1-format","read-only":false,"driver":"qcow2","file":"libvirt-1-storage","backing":null}' \
  -device '{"driver":"scsi-hd","bus":"scsi0.0","channel":0,"scsi-id":0,"lun":0,"device_id":"drive-scsi0-0-0-0","drive":"libvirt-1-format","id":"scsi0-0-0-0","bootindex":1,"wwn":408646137015301656}' \
  -netdev '{"type":"tap","fd":"33","vhost":true,"vhostfd":"35","id":"hostnet0"}' \
  -device '{"driver":"virtio-net-pci","netdev":"hostnet0","id":"net0","mac":"52:54:00:56:5b:08","bus":"pci.1","addr":"0x0"}' \
  -chardev socket,id=charchannel0,fd=30,server=on,wait=off \
  -device '{"driver":"virtserialport","bus":"virtio-serial0.0","nr":1,"chardev":"charchannel0","id":"channel0","name":"org.qemu.guest_agent.0"}' \
  -chardev socket,id=chrtpm,path=/run/libvirt/qemu/swtpm/2-workstation-w11-swtpm.sock \
  -tpmdev emulator,id=tpm-tpm0,chardev=chrtpm \
  -device '{"driver":"tpm-tis","tpmdev":"tpm-tpm0","id":"tpm0"}' \
  -audiodev '{"id":"audio1","driver":"none"}' \
  -device vfio-pci,host=65:00.0,id=hostdev0,bus=pci.6,addr=0x0 \
  -device vfio-pci,host=65:00.1,id=hostdev1,bus=pci.7,addr=0x0 \
  -device '{"driver":"virtio-balloon-pci","id":"balloon0","bus":"pci.8","addr":"0x0"}' \
  -object '{"qom-type":"rng-random","id":"objrng0","filename":"/dev/urandom"}' \
  -device '{"driver":"virtio-rng-pci","rng":"objrng0","id":"rng0","bus":"pci.9","addr":"0x0"}' \
  -chardev socket,id=mon1,server=on,wait=off,path=/var/lib/libvirt/qemu/workstation-qmp.sock \
  -mon chardev=mon1,mode=control,pretty=on \
  -sandbox on,obsolete=deny,elevateprivileges=deny,spawn=deny,resourcecontrol=deny \
  -msg timestamp=on
