- name: Set up authorized_keys
  copy:
    src: ssh_authorized_keys
    dest: '/home/{{ ansible_user }}/.ssh/authorized_keys'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: Disable SSH password authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication no'
    state: present
  notify: restart-sshd
